quarkus.http.port=8080
quarkus.swagger-ui.always-include=true
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:54422/quarkus
quarkus.datasource.username=quarkus
quarkus.datasource.password=quarkus
quarkus.datasource.db-kind=quarkus
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.disable-validation=true
quarkus.log.console.enable=true
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n
